Restaurante02/Restaurante02/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurante02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurante02.Controllers
{
    public class ClienteController : Controller
    {
        public Contexto Contexto { get; set; }

        public ClienteController(Contexto novoContexto)
        {
            this.Contexto = novoContexto;
        }

        // GET: ClienteController
        public ActionResult Index()
        {
            List<Cliente> clientes = Contexto.Clientes.ToList();
            return View(clientes);
        }

        // GET: ClienteController/Details/5
        public ActionResult Details(int id)
        {
            Cliente cliente = Contexto.Clientes.Where(e => e.Id == id).First();
            return View(cliente);
        }

        // GET: ClienteController/Create
        public ActionResult Create()
        {
            Cliente cliente = new Cliente();
            return View(cliente);
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cliente cliente)
        {
            try
            {
                Contexto.Clientes.Add(cliente);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Edit/5
        public ActionResult Edit(int id)
        {
            Cliente cliente = Contexto.Clientes.Where(e => e.Id == id).First();
            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Cliente cliente)
        {
            try
            {
                Contexto.Clientes.Update(cliente);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Delete/5
        public ActionResult Delete(int id)
        {

            Cliente cliente = Contexto.Clientes.Where(e => e.Id == id).First();
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Cliente cliente)
        {
            try
            {
                Contexto.Clientes.Remove(cliente);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Restaurante02/Restaurante02/Controllers/Item_PratoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurante02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurante02.Controllers
{
    public class Item_PratoController : Controller
    {
        public Contexto Contexto { get; set; }

        public Item_PratoController(Contexto novoContexto)
        {
            this.Contexto = novoContexto;
        }

        // GET: Item_PratoController
        public ActionResult Index()
        {
            List<Item_Prato> item_Pratos = Contexto.Item_Pratos.ToList();
            return View(item_Pratos);
        }

        // GET: Item_PratoController/Details/5
        public ActionResult Details(int id)
        {
            Item_Prato item_Prato = Contexto.Item_Pratos.Where(e => e.Id == id).First();
            return View(item_Prato);
        }

        // GET: Item_PratoController/Create
        public ActionResult Create()
        {
            Item_Prato item_Prato = new Item_Prato();
            return View(item_Prato);
        }

        // POST: Item_PratoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item_Prato item_Prato)
        {
            try
            {
                Contexto.Item_Pratos.Add(item_Prato);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Item_PratoController/Edit/5
        public ActionResult Edit(int id)
        {
            Item_Prato item_Prato = Contexto.Item_Pratos.Where(e => e.Id == id).First();
            return View(item_Prato);
        }

        // POST: Item_PratoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Item_Prato item_Prato)
        {
            try
            {
                Contexto.Item_Pratos.Update(item_Prato);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Item_PratoController/Delete/5
        public ActionResult Delete(int id)
        {

            Item_Prato item_Prato = Contexto.Item_Pratos.Where(e => e.Id == id).First();
            return View(item_Prato);
        }

        // POST: Item_PratoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Item_Prato item_Prato)
        {
            try
            {
                Contexto.Item_Pratos.Remove(item_Prato);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Restaurante02/Restaurante02/Controllers/PratoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurante02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurante02.Controllers
{
    public class PratoController : Controller
    {
        public Contexto Contexto { get; set; }

        public PratoController(Contexto novoContexto)
        {
            this.Contexto = novoContexto;
        }

        // GET: PratoController
        public ActionResult Index()
        {
            List<Prato> pratos = Contexto.Pratos.ToList();
            return View(pratos);
        }

        // GET: PratoController/Details/5
        public ActionResult Details(int id)
        {
            Prato prato = Contexto.Pratos.Where(e => e.Id == id).First();
            return View(prato);
        }

        // GET: PratoController/Create
        public ActionResult Create()
        {
            Prato prato = new Prato();
            return View(prato);
        }

        // POST: PratoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Prato prato)
        {
            try
            {
                Contexto.Pratos.Add(prato);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PratoController/Edit/5
        public ActionResult Edit(int id)
        {
            Prato prato = Contexto.Pratos.Where(e => e.Id == id).First();
            return View(prato);
        }

        // POST: PratoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Prato prato)
        {
            try
            {
                Contexto.Pratos.Update(prato);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PratoController/Delete/5
        public ActionResult Delete(int id)
        {

            Prato prato = Contexto.Pratos.Where(e => e.Id == id).First();
            return View(prato);
        }

        // POST: PratoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Prato prato)
        {
            try
            {
                Contexto.Pratos.Remove(prato);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Restaurante02/Restaurante02/Controllers/VendaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurante02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurante02.Controllers
{
    public class VendaController : Controller
    {
        public Contexto Contexto { get; set; }

        public VendaController(Contexto novoContexto)
        {
            this.Contexto = novoContexto;
        }

        // GET: VendaController
        public ActionResult Index()
        {
            List<Venda> vendas = Contexto.Vendas.ToList();
            return View(vendas);
        }

        // GET: VendaController/Details/5
        public ActionResult Details(int id)
        {
            Venda venda = Contexto.Vendas.Where(e => e.Id == id).First();
            return View(venda);
        }

        // GET: VendaController/Create
        public ActionResult Create()
        {
            Venda venda = new Venda();
            return View(venda);
        }

        // POST: VendaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Venda venda)
        {
            try
            {
                Contexto.Vendas.Add(venda);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VendaController/Edit/5
        public ActionResult Edit(int id)
        {
            Venda venda = Contexto.Vendas.Where(e => e.Id == id).First();
            return View(venda);
        }

        // POST: VendaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Venda venda)
        {
            try
            {
                Contexto.Vendas.Update(venda);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VendaController/Delete/5
        public ActionResult Delete(int id)
        {

            Venda venda = Contexto.Vendas.Where(e => e.Id == id).First();
            return View(venda);
        }

        // POST: VendaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Venda venda)
        {
            try
            {
                Contexto.Vendas.Remove(venda);
                Contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Restaurante02/Restaurante02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurante02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-danger bg-danger border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand bg-warning p-2" asp-area="" asp-controller="Home" asp-action="Index">Restaurante02</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Restaurante" asp-action="Index">Restaurante</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Ingrediente" asp-action="Index">Ingrediente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Prato" asp-action="Index">Prato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Item_Prato" asp-action="Index">Item_Prato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Venda" asp-action="Index">Venda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Item_Venda" asp-action="Index">Item_Venda</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Restaurante02 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>